# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy

on:
  push:
    branches: [cicd]

env:
  PM2_NAMESPACE: weup-learning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: yarn install

      - name: Build application
        run: |
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: .next/
          retention-days: 1

  deploy-develop:
    needs: build
    runs-on: ubuntu-latest
    environment: secret
    if: github.ref == 'refs/heads/cicd'

    env:
      DEPLOY_DIR: ~/weup-elearning
      APP_NAME: weup-elearning
      PORT: 5000
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: .next/

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          # Create deployment directory and deploy files
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ env.DEPLOY_DIR }}"
          scp -i ~/.ssh/id_rsa -r ./.next/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.DEPLOY_DIR }}/.next

      - name: Setup environment
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ env.DEPLOY_DIR }} && \
            cat > .env << EOF
          NEXT_PUBLIC_APP_URL=${{ env.NEXT_PUBLIC_APP_URL }}
          EOF"

      - name: Start/Restart PM2 application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ env.DEPLOY_DIR }} && \
            if pm2 list --namespace ${{ env.PM2_NAMESPACE }} | grep -q '${{ env.APP_NAME }}'; then
              pm2 restart ${{ env.APP_NAME }} --namespace ${{ env.PM2_NAMESPACE }} --update-env
            else
              pm2 start npm -- start --name ${{ env.APP_NAME }} --namespace ${{ env.PM2_NAMESPACE }}
            fi"

      - name: Cleanup SSH
        if: always()
        run: rm -f ~/.ssh/id_rsa
